image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

.rules_build: &rules_build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: always
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always

build:
  stage: build
  <<: *rules_build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  <<: *rules_build
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - build/libs/*.jar

deploy:
  stage: deploy
  script:
    - curl -fL https://getcli.jfrog.io | sh
    - ./jfrog rt config --url=$ARTIFACTORY_URL --apikey=$ARTIFACTORY_API_KEY
    - ./jfrog rt u "build/libs/*.jar" devops-1c/trunc-db-1c/trunc-db-1c.jar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/libs/*.jar
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" && $CI_COMMIT_TAG'
      when: always