name: Sonar

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: ''
      - run: |
          git fetch --prune --unshallow
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: SonarCloud Scan
        run: ./gradlew check sonarqube
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.projectKey=astrizhachuk_trunc-db-1c
          -Dsonar.organization=astrizhachuk
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
